# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x', '8.0.x', '9.0.x' ]
    env:
      working-directory: ./

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Display dotnet version
      run: dotnet --version
      
    - name: Update TargetFramework
      run: |
        # Extract major version from dotnet-version (e.g., '7.0.x' -> 'net7.0')
        TARGET_FRAMEWORK="net$(echo ${{ matrix.dotnet-version }} | cut -d'.' -f1).0"
        
        # Replace <TargetFramework> in all .csproj files
        find . -name '*.csproj' -exec sed -i "s|<TargetFramework>.*</TargetFramework>|<TargetFramework>${TARGET_FRAMEWORK}</TargetFramework>|" {} +
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}

    - name: Build the project
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}

    - name: Run test
      run: dotnet test --configuration Release --no-build --verbosity normal
