# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - dotnet-version: '7.0.x'
            target-framework: 'net7.0'
          - dotnet-version: '8.0.x'
            target-framework: 'net8.0'
    env:
      working-directory: ./

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup dotnet ${{ matrix.configuration.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.configuration.dotnet-version }}
        
    - name: Display dotnet version
      run: dotnet --version

    - name: Build the project
      run: dotnet build --configuration Release --framework ${{ matrix.configuration.target-framework }}
      working-directory: ${{env.working-directory}}

    - name: Run test
      run: dotnet test --configuration Release --no-build --framework ${{ matrix.configuration.target-framework }} --verbosity normal
